---
-name: Deploy to Tomcat
 hosts: web
 become: yes
 
 task: 
  -name: Copy WAR file to Tomcat
  
  copy:
  	src: "/var/snap/jenkins/5022/workspace/maven112/maven112.war"
  	
  	dest: "/opt/tomcat/webapp/maven112.war"
  	
  	remote_src: no
  	
  -name: Restart Tomcat
  	shell:
  		/opt/tomcat/bin/shutdown.sh
  		sleep 5
  		/opt/tomcat/bin/startup.sh
